version: "3.5"

services:
  one-hour-front:
    build:
      context: .
      dockerfile: Dockerfile #-ci
    restart: always
    ports:
      - 8010:80
    environment:
      - REACT_APP_API_URL=https://api.sansoft-inn.com/one-hour/
