version: "3.5"

services:
  one-hour-front:
    image: one-hour-front
    ports:
      - "8010:80"
    environment:
      - REACT_APP_API_URL=https://api.sansoft-inn.com/one-hour/
    networks:
      - one-hour

networks:
  one-hour:
    external:
      name: 'one-hour-network'
